apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
spec:
  selector:
    app: ml-app
  ports:
    - protocol: TCP
      port: 8082  # Change to 8082 for Jenkins if needed
      targetPort: 8080  # Change accordingly
  type: LoadBalancer
